

<img src="https://huggingface.co/front/assets/huggingface_logo-noborder.svg" alt="Hugging Face Logo" width="40" style="vertical-align:middle;"/>
<a href="https://huggingface.co/spaces/RahmaNh/Kategori_Berita_svd" target="_blank" style="text-decoration:none; font-size:16px; margin-left:10px;">HuggingFace Klasifikasi (svd)</a>

# Penerapan Logistic Regression (SVD)

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/PPW/tugas/preprocessing-cnnnews.csv")
df.head()

,judul,isi,tanggal,kategori,berita_clean,case_folding,tokenize,stopword_removal
0,Jokowi Groundbreaking 2 Investasi Asing di IKN...,Presiden Joko Widodo (Jokowi) dijadwalkan mela...,"Selasa, 10 Sep 2024 20:02 WIB",Ekonomi,Presiden Joko Widodo Jokowi dijadwalkan melaku...,presiden joko widodo jokowi dijadwalkan melaku...,"['presiden', 'joko', 'widodo', 'jokowi', 'dija...",presiden joko widodo jokowi dijadwalkan peleta...
1,Amran Copot Direktur Diduga Calo Pengadaan Bar...,Menteri Pertanian Andi Amran Sulaiman mencopot...,"Selasa, 10 Sep 2024 19:11 WIB",Ekonomi,Menteri Pertanian Andi Amran Sulaiman mencopot...,menteri pertanian andi amran sulaiman mencopot...,"['menteri', 'pertanian', 'andi', 'amran', 'sul...",menteri pertanian andi amran sulaiman mencopot...
2,Bahlil Bicara Pasokan Listrik di Tengah Rencan...,Menteri Energi dan Sumber Daya Mineral (ESDM) ...,"Selasa, 10 Sep 2024 18:32 WIB",Ekonomi,Menteri Energi dan Sumber Daya Mineral ESDM Ba...,menteri energi dan sumber daya mineral esdm ba...,"['menteri', 'energi', 'dan', 'sumber', 'daya',...",menteri energi sumber daya mineral esdm bahlil...
3,Pertamina Kaji Ubah Minyak Jelantah Jadi Avtur,PT Pertamina (Persero) mengkaji pengembangan b...,"Selasa, 10 Sep 2024 17:43 WIB",Ekonomi,PT Pertamina Persero mengkaji pengembangan bah...,pt pertamina persero mengkaji pengembangan bah...,"['pt', 'pertamina', 'persero', 'mengkaji', 'pe...",pt pertamina persero mengkaji pengembangan bah...
4,"Dukung PMI, Bank Mandiri Perluas Akses Livin' ...",Bank Mandiri menghadirkan program Livin' Aroun...,"Selasa, 10 Sep 2024 17:18 WIB",Ekonomi,Bank Mandiri menghadirkan program Livin Around...,bank mandiri menghadirkan program livin around...,"['bank', 'mandiri', 'menghadirkan', 'program',...",bank mandiri menghadirkan program livin around...

## Split Data

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df['stopword_removal'], df['kategori'], test_size=0.2, random_state=42)

## TFIDF

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X_train_tfidf = vectorizer.fit_transform(X_train)  # Fit-transform pada data latih
X_test_tfidf = vectorizer.transform(X_test)        # Transformasi data uji dengan model TF-IDF yang sama

# Mengubah hasilnya menjadi DataFrame
X_train_tfidf_df = pd.DataFrame(X_train_tfidf.toarray(), columns=vectorizer.get_feature_names_out())
print("TFIDF: DATA TRAINING")
X_train_tfidf_df

TFIDF: DATA TRAINING

,abad,abdul,abinisa,absen,absrhr,abu,acara,aceh,acehsumatera,acehsumut,...,yudha,yudo,yugen,yulianto,zaenal,zayana,zero,zona,zulhas,zulkifli
0,0.00000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
1,0.00000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
2,0.00000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
3,0.00000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
4,0.00000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.00000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.097544,0.0,0.0
76,0.00000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
77,0.03463,0.0,0.0,0.0,0.0,0.000000,0.094205,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
78,0.00000,0.0,0.0,0.0,0.0,0.059701,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
79,0.00000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.127533,0.045017,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0

In [5]:
# Mengubah hasil transformasi X_test_tfidf menjadi DataFrame
X_test_tfidf_df = pd.DataFrame(X_test_tfidf.toarray(), columns=vectorizer.get_feature_names_out())
print("TFIDF: DATA TESTING")
X_test_tfidf_df

TFIDF: DATA TESTING

,abad,abdul,abinisa,absen,absrhr,abu,acara,aceh,acehsumatera,acehsumut,...,yudha,yudo,yugen,yulianto,zaenal,zayana,zero,zona,zulhas,zulkifli
0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.040845,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## SVD

In [6]:
from sklearn.decomposition import TruncatedSVD
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

svd = TruncatedSVD(n_components=50, random_state=42) # komponen
X_train_svd = svd.fit_transform(X_train_tfidf)
X_test_svd = svd.transform(X_test_tfidf)

print(X_test_svd.shape)

(20, 50)

In [7]:
X_train_svd_df = svd_df = pd.DataFrame(X_train_svd)
X_train_svd_df

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,0.572740,0.032930,-0.037824,0.129799,-0.005688,-0.114952,0.022043,-0.049946,-0.017240,0.000435,...,0.014118,-0.044539,0.021622,0.047097,0.187849,-0.040159,-0.013389,-0.159711,-0.007173,0.096375
1,0.409329,-0.044119,-0.024222,-0.125055,-0.065580,-0.155073,-0.002638,0.009818,0.005354,-0.000111,...,0.133319,0.072263,-0.115315,0.275505,-0.106370,0.085952,-0.114507,-0.080689,-0.099316,-0.103445
2,0.056392,0.447721,0.696876,-0.050303,-0.231623,0.062068,0.146309,0.018703,-0.029776,-0.028423,...,0.006436,-0.012677,-0.012970,-0.003278,0.003282,-0.025137,0.009429,0.015339,-0.001528,0.011111
3,0.010404,0.110688,0.021136,-0.007196,0.077672,-0.036559,-0.064572,-0.030738,-0.011708,-0.066571,...,0.094608,-0.018318,0.103667,-0.044754,0.014526,0.022049,0.073607,-0.035855,-0.057184,0.053290
4,0.560042,-0.016372,-0.037390,-0.066619,-0.016927,-0.076853,0.020033,-0.022122,0.009081,-0.017826,...,0.001550,0.044186,-0.025598,0.137391,0.042100,0.008573,-0.100198,0.024241,-0.089444,0.265450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.727203,-0.049384,-0.049258,-0.221139,-0.099842,-0.019360,-0.056032,0.091979,0.031463,-0.025370,...,-0.003679,0.003139,-0.009490,-0.006015,0.015480,0.005394,-0.019319,-0.098247,-0.029021,-0.085124
76,0.302202,0.006112,-0.040726,-0.362209,0.050209,0.616087,-0.138952,-0.019715,-0.000691,0.013069,...,0.032144,-0.033177,-0.004693,0.017873,0.060488,-0.037794,-0.004764,-0.048171,0.099591,0.030917
77,0.026835,0.044508,0.020459,0.004176,0.046997,-0.007218,-0.028215,0.037553,-0.041780,0.078120,...,0.079161,0.131259,0.026697,0.012482,0.056198,0.052669,0.063165,0.027018,0.017489,0.007346
78,0.243471,0.024860,0.009641,-0.123399,0.009479,0.082070,0.084998,-0.261987,-0.103047,0.061353,...,0.038232,0.218497,-0.050087,-0.019258,0.153459,-0.105263,0.053778,-0.110143,0.133908,-0.029102
79,0.079268,0.099190,0.021967,-0.085858,0.348880,0.008760,0.260950,-0.030503,-0.026724,0.049084,...,0.068833,-0.211978,-0.035551,0.070214,-0.182363,-0.089866,-0.089446,-0.031255,0.377257,-0.032000

## Penerapan Logistic Regression

In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report

In [9]:
# kolom yang berisi label target
y = df['kategori']

In [10]:
# Membuat model Logistic Regression
logreg = LogisticRegression()
logreg.fit(X_train_svd, y_train)

LogisticRegression()

In [11]:
y_pred = logreg.predict(X_test_svd)

In [12]:
# Hitung metrik evaluasi
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')  # Gunakan average='weighted' untuk kelas tidak seimbang
recall = recall_score(y_test, y_pred, average='weighted')

# Tampilkan hasil
print(f"Akurasi: {accuracy:.4f}")
print(f"Presisi: {precision:.4f}")
print(f"Recall: {recall:.4f}")

# Atau tampilkan laporan klasifikasi lengkap
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Akurasi: 1.0000
Presisi: 1.0000
Recall: 1.0000

Classification Report:
              precision    recall  f1-score   support

     Ekonomi       1.00      1.00      1.00        12
    Olahraga       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

In [13]:
import pickle

# Simpan TfidfVectorizer
with open('tfidf_vectorizer.pkl', 'wb') as file:
    pickle.dump(vectorizer, file)

In [14]:
import pickle

# Simpan TfidfVectorizer
with open('svd.pkl', 'wb') as file:
    pickle.dump(svd, file)

In [15]:
# Simpan model Logistic Regression ke file pickle
with open('model_logreg.pkl', 'wb') as f:
    pickle.dump(logreg, f)

print("Model Logistic Regression telah disimpan ke file 'model_logreg.pkl'")

Model Logistic Regression telah disimpan ke file 'model_logreg.pkl'

In [17]:
import pickle
import pandas as pd

# Muat pipeline preprocessing dan TF-IDF dari file pickle
with open('tfidf_vectorizer.pkl', 'rb') as f:
    pipeline = pickle.load(f)

with open('svd.pkl', 'rb') as f:
    svd_pipeline = pickle.load(f)


# Muat model Logistic Regression dari file pickle
with open('model_logreg.pkl', 'rb') as f:
    model_logreg = pickle.load(f)

# Data baru yang ingin diuji
data_baru = [
    "Pasar saham mengalami penurunan tajam setelah adanya laporan ketidakpastian ekonomi global. Investor disarankan untuk berhati-hati dalam mengambil keputusan terkait investasi.",
    "Duel berjalan lebih sengit di babak kedua. Palace berani mengambil inisiatif menyerang dan mampu menciptakan peluang-peluang berbahaya. Tuan rumah nyaris unggul pada menit ke-65 namun Andre Onana berhasil menggagalkan dua ancaman serius. Onana melakukan double save dari tembakan Eddie Nketiah dan Ismaila Sarr.Nketiah lebih dulu melepaskan tembakan dari luar kotak penalti dan berhasil ditepis Onana. Bola liar kemudian coba disambar Sarr tapi lagi-lagi bisa diblok sang penjaga gawangMU tampak kesulitan membangun serangan karena pressing ketat yang dilakukan para pemain Palace. Sering kali serangan yang dibangun Bruno Fernandes dkk terputus di tengah jalan.Hasil imbang tanpa gol tak terhindarkan hingga laga usai. Raihan satu poin merugikan Man Utd yang tengah berjuang kembali ke papan atas klasemen sementara. Kedua penjaga gawang kesebelasan, Henderson dan Onana, patut diacungi jempol berkat penyelamatan gemilang yang dilakukan di sepanjang pertandingan."
]

# Mengubah data baru ke dalam DataFrame
data_baru_df = pd.Series(data_baru)

# Proses data baru menggunakan pipeline
tfidf_baru = pipeline.transform(data_baru_df)

svd_baru =svd_pipeline.transform(tfidf_baru)

# Prediksi kategori berita menggunakan model Logistic Regression
prediksi = model_logreg.predict(svd_baru)

# Tampilkan hasil prediksi
for i, text in enumerate(data_baru):
    print(f"Teks: {text}\nPrediksi Kategori: {prediksi[i]}\n")

Teks: Pasar saham mengalami penurunan tajam setelah adanya laporan ketidakpastian ekonomi global. Investor disarankan untuk berhati-hati dalam mengambil keputusan terkait investasi.
Prediksi Kategori: Ekonomi

Teks: Duel berjalan lebih sengit di babak kedua. Palace berani mengambil inisiatif menyerang dan mampu menciptakan peluang-peluang berbahaya. Tuan rumah nyaris unggul pada menit ke-65 namun Andre Onana berhasil menggagalkan dua ancaman serius. Onana melakukan double save dari tembakan Eddie Nketiah dan Ismaila Sarr.Nketiah lebih dulu melepaskan tembakan dari luar kotak penalti dan berhasil ditepis Onana. Bola liar kemudian coba disambar Sarr tapi lagi-lagi bisa diblok sang penjaga gawangMU tampak kesulitan membangun serangan karena pressing ketat yang dilakukan para pemain Palace. Sering kali serangan yang dibangun Bruno Fernandes dkk terputus di tengah jalan.Hasil imbang tanpa gol tak terhindarkan hingga laga usai. Raihan satu poin merugikan Man Utd yang tengah berjuang kembali ke papan atas klasemen sementara. Kedua penjaga gawang kesebelasan, Henderson dan Onana, patut diacungi jempol berkat penyelamatan gemilang yang dilakukan di sepanjang pertandingan.
Prediksi Kategori: Olahraga