# Part.6 Pencarian Dokumen


**RAHMA** **NURHALIZA** (**210411100176**)

**PPW** **A**

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_similarity
import re
from IPython.display import display, Markdown

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/PPW/tugas/preprocessing-cnnnews.csv")
df.head()

,judul,isi,tanggal,kategori,berita_clean,case_folding,tokenize,stopword_removal
0,Jokowi Groundbreaking 2 Investasi Asing di IKN...,Presiden Joko Widodo (Jokowi) dijadwalkan mela...,"Selasa, 10 Sep 2024 20:02 WIB",Ekonomi,Presiden Joko Widodo Jokowi dijadwalkan melaku...,presiden joko widodo jokowi dijadwalkan melaku...,"['presiden', 'joko', 'widodo', 'jokowi', 'dija...",presiden joko widodo jokowi dijadwalkan peleta...
1,Amran Copot Direktur Diduga Calo Pengadaan Bar...,Menteri Pertanian Andi Amran Sulaiman mencopot...,"Selasa, 10 Sep 2024 19:11 WIB",Ekonomi,Menteri Pertanian Andi Amran Sulaiman mencopot...,menteri pertanian andi amran sulaiman mencopot...,"['menteri', 'pertanian', 'andi', 'amran', 'sul...",menteri pertanian andi amran sulaiman mencopot...
2,Bahlil Bicara Pasokan Listrik di Tengah Rencan...,Menteri Energi dan Sumber Daya Mineral (ESDM) ...,"Selasa, 10 Sep 2024 18:32 WIB",Ekonomi,Menteri Energi dan Sumber Daya Mineral ESDM Ba...,menteri energi dan sumber daya mineral esdm ba...,"['menteri', 'energi', 'dan', 'sumber', 'daya',...",menteri energi sumber daya mineral esdm bahlil...
3,Pertamina Kaji Ubah Minyak Jelantah Jadi Avtur,PT Pertamina (Persero) mengkaji pengembangan b...,"Selasa, 10 Sep 2024 17:43 WIB",Ekonomi,PT Pertamina Persero mengkaji pengembangan bah...,pt pertamina persero mengkaji pengembangan bah...,"['pt', 'pertamina', 'persero', 'mengkaji', 'pe...",pt pertamina persero mengkaji pengembangan bah...
4,"Dukung PMI, Bank Mandiri Perluas Akses Livin' ...",Bank Mandiri menghadirkan program Livin' Aroun...,"Selasa, 10 Sep 2024 17:18 WIB",Ekonomi,Bank Mandiri menghadirkan program Livin Around...,bank mandiri menghadirkan program livin around...,"['bank', 'mandiri', 'menghadirkan', 'program',...",bank mandiri menghadirkan program livin around...

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df['isi'], df['kategori'], test_size=0.2, random_state=42)

## TF-IDF

In [ ]:
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(df['stopword_removal'])
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=vectorizer.get_feature_names_out())
tfidf_df.head(200)

,abad,abdul,abdulhadi,abinisa,absen,absjal,absrhr,abu,acara,aceh,...,yudo,yugen,yuk,yulianto,zaenal,zayana,zero,zona,zulhas,zulkifli
0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.024308,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.088183,0.000000,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.047426,0.000000,0.000000,0.0,0.0
96,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0
97,0.0,0.0,0.0,0.0,0.0,0.0,0.106948,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0
98,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0
99,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.053279,0.0,0.0

## Reduksi Dimensi dengan  Truncated SVD

In [ ]:
svd = TruncatedSVD(n_components=100, random_state=42)  # Mulai dengan 100 komponen, bisa dikurangi lagi nanti
tfidf_svd_matrix = svd.fit_transform(tfidf_matrix)
svd_df = pd.DataFrame(tfidf_svd_matrix)
#Transpose matriks hasil SVD
#tfidf_svd_matrix_transposed = tfidf_svd_matrix.T
svd_df.head(100)
#svd_df.shape

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.064586,0.188992,0.008672,-0.027832,-0.006030,-0.147161,0.286516,0.018550,0.119475,-0.008067,...,0.011600,0.019177,0.015856,-0.004680,-0.016401,0.002696,0.000870,0.001023,-0.000633,0.001782
1,0.016457,0.179865,-0.013202,0.021377,0.077344,0.031816,0.088990,0.029517,0.107614,-0.129625,...,0.003997,-0.028164,0.000970,-0.006774,0.002675,-0.000255,-0.001913,0.002492,-0.001593,-0.002080
2,0.031062,0.144795,-0.010155,-0.003804,0.010489,-0.027065,0.007119,0.199850,-0.069954,-0.003941,...,-0.005434,-0.002698,-0.001227,0.000231,-0.000904,0.000405,-0.000557,-0.000371,-0.000362,-0.000086
3,0.047709,0.195778,-0.012764,-0.003038,-0.012011,-0.085911,-0.055248,0.161753,-0.076000,0.030667,...,0.001599,0.009062,-0.009052,-0.002909,0.002805,-0.001042,0.001103,0.001390,-0.001164,-0.000268
4,0.052167,0.133710,-0.009733,-0.010554,0.015350,-0.009544,0.048062,0.100011,0.037437,-0.004073,...,-0.008579,-0.011129,-0.000627,0.006025,-0.005575,0.000272,-0.000378,0.000010,0.001317,0.000176
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.114567,0.043904,0.010629,0.000050,0.042504,-0.057286,0.129163,-0.039097,-0.084506,-0.011177,...,-0.001750,0.002290,0.002323,-0.003260,0.002104,0.001595,0.001329,0.000764,-0.000653,-0.001204
96,0.154076,0.024865,0.043760,0.007618,-0.013868,0.006646,0.006122,-0.016914,-0.068085,-0.151474,...,0.000436,0.009560,0.014421,-0.007335,-0.000831,0.009769,-0.004656,0.001117,-0.002290,0.001260
97,0.559221,-0.018326,-0.094225,-0.064428,0.029930,-0.003415,-0.002151,-0.018271,-0.023394,-0.141488,...,-0.004422,0.000370,-0.025488,-0.045139,-0.005575,0.011777,0.016205,0.003124,0.006595,0.009041
98,0.545225,-0.022100,-0.124938,-0.021011,0.013938,-0.005100,0.013414,-0.001562,-0.017073,-0.213457,...,0.003371,-0.006210,-0.028595,-0.019757,0.008564,0.012005,0.002918,-0.003305,-0.009059,0.006263
99,0.501762,0.006642,-0.052377,-0.019273,0.042294,-0.016383,0.000789,-0.034977,-0.010077,-0.053142,...,0.016435,-0.001062,0.057775,-0.204360,0.002141,0.017582,0.009432,-0.000710,-0.002712,0.007553

## Transform query ke bentuk TF-IDF dan reduksi SVD

In [ ]:
#Transform query ke bentuk TF-IDF dan reduksi SVD
query = input("Masukkan kalimat yang ingin dicari: ")  # Ganti dengan kalimat yang ingin dicari
query_tfidf = vectorizer.transform([query])
query_svd = svd.transform(query_tfidf)
query_df = pd.DataFrame(query_svd)
#query_df

Masukkan kalimat yang ingin dicari: indonesia vs australia

## Hitung kemiripan (cosine similarity) antara query dan dokumen di dimensi yang lebih rendah

In [ ]:
cosine_similarities = cosine_similarity(query_svd, tfidf_svd_matrix).flatten()

In [ ]:
similarity_threshold = 0.5
related_docs_indices = [i for i, sim in enumerate(cosine_similarities) if sim > similarity_threshold]
related_documents = df.iloc[related_docs_indices].copy()
related_documents['similarity'] = cosine_similarities[related_docs_indices]  # Tambahkan kolom similarity

print("kalimat yang dicari:",query)

# Menampilkan dokumen terkait dengan format yang diinginkan
print("=" * 50)
print(f"{'Dokumen Terkait':^50}")
print("=" * 50)
displayed_count = 0

for index, row in related_documents.iterrows():
    print(f"Dokumen #{displayed_count + 1}")
    print(f"Judul     : {row['judul']}")
    print(f"Tanggal   : {row['tanggal']}")
    print(f"Kategori  : {row['kategori']}")
    print(f"Similarity: {row['similarity']:.4f}")
    print(f"Isi Berita:\n{row['isi']}")
    print("-" * 50)  # Pemisah antar dokumen
    displayed_count += 1

# Menampilkan jumlah dokumen yang ditampilkan
print(f"\nJumlah dokumen yang ditampilkan: {displayed_count}")
print("=" * 50)

kalimat yang dicari: indonesia vs australia
==================================================
                 Dokumen Terkait
==================================================
Dokumen #1
Judul     : Link Live Streaming Indonesia vs Australia di Kualifikasi Piala Dunia
Tanggal   : Selasa, 10 Sep 2024 17:04 WIB
Kategori  : Olahraga
Similarity: 0.5799
Isi Berita:
Link live streaming Timnas Indonesia vs Australia di putaran ketiga Kualifikasi Piala Dunia 2026 Zona Asia dapat dilihat dari artikel berikut. Timnas Indonesia akan menjalani laga kedua di Grup C Kualifikasi Piala Dunia 2026 Zona Asia dengan menghadapi Australia. Laga ini akan berlangsung hari ini Selasa (10/9) malam WIB di Stadion Utama Gelora Bung Karno, Jakarta. Jadwal Siaran langsung Timnas Indonesia vs Australia akan disiarkan RCTI pada Selasa (10/9) pukul 19.00 WIB. Selain itu, laga kandang pertama Timnas Indonesia pada fase ketiga Kualifikasi Piala Dunia 2026 ini juga dapat disaksikan melalui live streaming di Vision+. Pilihan Redaksi Jadwal Siaran Langsung Timnas Indonesia vs Australia Prediksi Timnas Indonesia vs Australia di Kualifikasi Piala Dunia Prediksi Line Up Indonesia vs Australia di Kualifikasi Piala Dunia Laga kedua ini menjadi krusial bagi masing-masing tim. Timnas Indonesia ingin melanjutkan tren positif setelah menahan imbang Arab Saudi di Jeddah. Kini di hadapan ribuan suporter setia, Rizky Ridho dan kawan-kawan akan bersikeras memetik poin penuh pada laga malam nanti. Dalam fase pertama dan kedua Kualifikasi Piala Dunia 2026, Timnas Indonesia sudah menjalani empat laga kandang yang berakhir dengan tiga kemenangan dan sekali kalah. Di sisi lain, tim tamu asuhan Graham Arnold bertandang ke Jakarta bukan tanpa motivasi. Kekalahan 0-1 dari Bahrain di kandang menjadi tamparan keras bagi Martin Boyle dkk. Australia diprediksi akan mendominasi penyerangan untuk menciptakan poin terlebih dahulu atas Timnas Indonesia. Catatan lima pertandingan tandang tak terkalahkan menjadi modal yang baik bagi Socceroos. Wasit Salman Ahmad Falahi akan memimpin pertandingan Timnas Indonesia vs Australia malam ini. Salman telah memimpin tiga pertandingan dalam Kualifikasi Piala Dunia 2026, dua dari tiga laga yang dipimpinnya dimenangi tuan rumah. Link Live Streaming Timnas Indonesia vs Australia di kualifikasi Piala Dunia 2026: Stadion Utama Gelora Bung Karno/ Selasa (10/9) pukul 19.00 WIB/ Vision+ [Gambas:Video CNN] (afr/nva)
--------------------------------------------------
Dokumen #2
Judul     : Perbandingan Ranking FIFA Timnas Indonesia vs Australia
Tanggal   : Selasa, 10 Sep 2024 10:03 WIB
Kategori  : Olahraga
Similarity: 0.5033
Isi Berita:
Timnas Indonesia dan Australia memiliki perbedaan ranking FIFA yang luar biasa menjelang duel kedua tim dalam babak ketiga Kualifikasi Piala Dunia 2026, Selasa (10/9). Timnas Indonesia menjamu Australia dalam laga kedua Grup C babak ketiga Kualifikasi Piala Dunia 2026 di Stadion Utama Gelora Bung Karno (GBK). Pertandingan ini jadi laga kandang pertama Indonesia dalam babak ketiga Kualifikasi Piala Dunia 2026. Baik Indonesia maupun Australia sama-sama mengincar hasil positif. Hanya saja, setelah dihajar Bahrain 0-1 dalam laga kandang, Australia bertekad menekuk Indonesia di kandangnya sendiri. Pilihan Redaksi Momen Timnas Indonesia Hajar Australia 1-0 di Kualifikasi Piala Dunia Profil Salman Falahi, Wasit Kontroversial di Indonesia vs Australia Gelora 10 November, Saksi Timnas Indonesia Tumpas Australia 1-0 Indonesia yang mengimbangi Arab Saudi 1-1 dalam pertandingan pertama juga berhasrat menang atas Australia. Akan tetapi, dengan melihat perbedaan ranking FIFA yang mencengangkan, hasil imbang sangat bagus untuk Skuad Garuda. Sebelum babak ketiga Kualifikasi Piala Dunia 2026 dimulai, Timnas Indonesia menempati peringkat ke-133 dalam ranking FIFA, berdasarkan rilis terakhir pada 18 Juli. Sementara, Australia unggul jauh atas Indonesia. The Socceroos unggul 109 setrip di atas Tim Merah Putih dengan menempati peringkat ke-24 dunia. Di level Asia, Australia menempati posisi keempat di bawah Jepang, Iran, dan Korea Selatan. Sedangkan Indonesia di peringkat ke-23 Asia. Pelatih Indonesia Shin Tae Yong mengakui perbedaan ranking membuat Australia layak lebih diunggulkan atas Indonesia. Meski begitu Jay Idzes dan kawan-kawan akan memberikan perlawanan kepada Australia. "Saya tidak bisa bicarakan taktik di sini, tetapi kita bisa lihat dari FIFA ranking, kita mau menyerang pun pasti (ujung-ujungnya) akan lebih banyak bertahan," ujar Shin Tae Yong dalam konferensi pers jelang laga. "FIFA ranking Australia 20-an, kita 130-an, mungkin saja 6:4. Tapi saya sebagai pelatih Timnas Indonesia bagaimana pun akan memikirkan (solusi) untuk itu," ucap Shin Tae Yong menambahkan. [Gambas:Video CNN] (sry/abs/jal)
--------------------------------------------------
Dokumen #3
Judul     : Prediksi Timnas Indonesia vs Australia di Kualifikasi Piala Dunia
Tanggal   : Selasa, 10 Sep 2024 09:31 WIB
Kategori  : Olahraga
Similarity: 0.6702
Isi Berita:
Timnas Indonesia melakoni laga berat melawan Australia dalam Kualifikasi Piala Dunia 2026 di Stadion utama Gelora Bung Karno (GBK), Selasa (10/9) malam. Berikut prediksi Indonesia vs Australia. Tuan rumah Indonesia sedang dalam motivasi tinggi menghadapi Australia setelah mengimbangi Arab Saudi pada pertandingan pertama. Sementara Australia dalam tekanan lantaran kalah 0-1 dari Bahrain. Meski begitu Indonesia pantang jemawa, lantaran Australia tidak seperti Arab Saudi. Australia memiliki kondisi tim yang lebih bagus. The Socceroos hanya kurang beruntung dalam penyelesaian akhir saat lawan Bahrain. Pilihan Redaksi Reaksi Calvin Verdonk Usai Followers Instagram Tembus 1 Juta Jadwal Siaran Langsung Timnas Indonesia vs Australia Profil Salman Falahi, Wasit Kontroversial di Indonesia vs Australia Apabila terlalu percaya diri dan kehilangan fokus, akan berbahaya bagi Indonesia dalam menghadapi Australia. Skuad Garuda butuh kerja keras dengan konsentrasi selama 90 menit. Kedodoran di babak kedua, khususnya pada menit-menit akhir jadi perhatian khusus bagi tim asuhan Shin Tae Yong ini. Apabila Maarten Paes dan kawan-kawan bisa konsisten selama pertandingan, bukan tidak mungkin Indonesia kembali mencuri poin dari Australia. Tambahan tenaga dari Justin Hubner yang sudah terbebas dari akumulasi kartu bisa makin menguatkan pertahanan Indonesia. Justun Hubner termasuk pemain yang fleksibel, bisa dimainkan di sektor pertahanan atau gelandang bertahan. Indonesia Tahan Australia (Surya Sumirat) Timnas Indonesia mendapat lawan berat, Australia. Kekuatan Australia lebih bagus ketimbang Arab Saudi. Ditambah lagi Australia bisa memainkan sejumlah pemain utama yang absen saat kalah dari Bahrain. Indonesia perlu konsisten dalam menyerang maupun bertahan menghadapi Australia. Apabila Indonesia lengah, gawang Maarten Paes bisa dalam ancaman. Namun jika Garuda bisa solid dan konsisten selama 90 menit, bukan tidak mungkin Indonesia kembali membuat kejutan dengan mencuri poin dari Australia. Saya prediksi Indonesia tahan Australia 0-0. Baca kelanjutan berita ini di halaman berikutnya... Stamina Bugar Jadi Tantangan bagi Timnas Indonesia BACA HALAMAN BERIKUTNYA HALAMAN: 1 2
--------------------------------------------------
Dokumen #4
Judul     : Gelora 10 November, Saksi Timnas Indonesia Tumpas Australia 1-0
Tanggal   : Selasa, 10 Sep 2024 09:00 WIB
Kategori  : Olahraga
Similarity: 0.5851
Isi Berita:
Stadion Gelora 10 November Surabaya menjadi saksi bisu kemenangan 1-0 Timnas Indonesia atas Australia dalam Kualifikasi Piala Dunia. Menjelang pertarungan sengit di Stadion Utama Gelora Bung Karno (GBK), Jakarta, Selasa (10/9) malam, Timnas Indonesia memiliki kenangan manis melawan Australia. Indonesia akan melawan Australia dalam laga kedua Grup C babak ketiga Kualifikasi Piala Dunia 2026 di GBK, malam nanti. Sebelum pertandingan krusial itu dimulai, Skuad Garuda punya rapor apik melawan The Socceroos di kandang. Pilihan Redaksi Momen Timnas Indonesia Hajar Australia 1-0 di Kualifikasi Piala Dunia 7 Fakta Menarik Jelang Timnas Indonesia vs Australia Reaksi Calvin Verdonk Usai Followers Instagram Tembus 1 Juta Rekor pertemuan kedua tim memihak Australia dengan 12 kemenangan dari 16 pertandingan sejak 1967, menurut situ Socceroos. Timnas Indonesia hanya menang satu kali pada Agustus 1981 silam. Kemenangan Indonesia atas Australia itu terjadi dalam Kualifikasi Piala Dunia 1982 zona Asia dan Oseania pada 1981. Laga Indonesia vs Australia di Stadion Gelora 10 November Surabaya tersebut merupakan partai pemungkas kedua tim di Grup 1. Kemenangan Indonesia atas Australia di Gelora 10 November itu jadi satu-satunya yang dimiliki Tim Merah Putih atas tim asal Oseania tersebut sampai saat ini. Laga Indonesia vs Australia tidak lagi menentukan bagi kedua tim. Pasalnya, baik Timnas Indonesia maupun Australia sama-sama dipastikan tidak lolos ke kualifikasi terakhir. Hanya saja, pertandingan yang dipimpin wasit R Reyes itu krusial bagi Indonesia demi menghindari posisi juru kunci di Grup 1. Sebelum pertandingan, Indonesia mengoleksi 4 poin hasil 1 kemenangan dan 2 kali imbang. Sejumlah sumber menyebutkan, kala itu Indonesia yang dilatih Endang Witarsa yang menggantikan Harry Tjong menurunkan sejumlah pemain muda yang diproyeksikan mengikuti FIFA World Youth Championship 1981 atau saat ini bernama Piala Dunia U-20. Dalam pertandingan tersebut para pemain Australia kelelahan karena cuaca panas di Surabaya. Situasi itu dimanfaatkan Indonesia dengan memiliki sejumlah peluang gol, namun finishing Tim Merah Putih buruk. Tekanan Indonesia baru membuahkan hasil pada menit-menit akhir pertandingan. Pada menit ke-88 striker Herry Risdianto membobol gawang Australia yang dijaga Glen Ahearn. Gol tersebut tercipta lewat kerja sama dua gelandang, Abdul Rahman dan Rully Nere. Kerja sama apik menjadi umpan matang bagi Risdianto yang melepaskan tembakan keras dari sudut sempit. Indonesia pun menang 1-0 atas Australia. Jadwal Siaran Langsung Timnas Indonesia vs Australia Kemenangan itu membuat Gelora 10 November jadi saksi sejarah satu-satunya laga yang dimenangkan Indonesia atas Australia di semua ajang sampai saat ini. Indonesia pun menempati peringkat ketiga klasemen Grup 1 dan terhindar dari dasar klasemen. Saat ini Timnas Indonesia dalam kondisi bagus dan memiliki kepercayaan diri tinggi setelah mengimbangi Arab Saudi dalam laga tandang. Sebaliknya, Australia memiliki beban lebih karena baru dikalahkan Bahrain di kandang sendiri. Kemenangan pada Augusts 1981 diharapkan kembali terulang setelah 43 tahun. Timnas Indonesia membutuhkan kemenangan guna menahbiskan diri sebagai 'kuda hitam' Grup C, sekaligus membuka peluang lolos ke putaran final Piala Dunia 2026. [Gambas:Video CNN] (sry)
--------------------------------------------------
Dokumen #5
Judul     : Jadwal Siaran Langsung Timnas Indonesia vs Australia
Tanggal   : Selasa, 10 Sep 2024 06:26 WIB
Kategori  : Olahraga
Similarity: 0.7697
Isi Berita:
Timnas Indonesia akan menjamu Australia di Stadion GBK. Berikut jadwal siaran langsung Timnas Indonesia vs Australia di Kualifikasi Piala Dunia 2026 malam ini. Jadwal Timnas Indonesia vs Australia pada matchday kedua Grup C putaran ketiga Kualifikasi Piala Dunia 2026 akan berlangsung di Stadion Utama Gelora Bung Karno, Senayan hari ini Selasa (10/9) malam WIB Siaran langsung Timnas Indonesia vs Australia bisa ditonton di RCTI mulai pukul 19.00 WIB. Pilihan Redaksi Momen Timnas Indonesia Hajar Australia 1-0 di Kualifikasi Piala Dunia Reaksi Calvin Verdonk Usai Followers Instagram Tembus 1 Juta Wasit Kontroversial Salman Falahi Pimpin Laga Indonesia vs Australia Selain itu duel Timnas Indonesia vs Australia juga bisa disaksikan melalui live streaming di Vision+ mulai pukul 19.00 WIB. Secara head to head, Indonesia dan Australia telah bertemu sejak 7 November 1967. Indonesia tercatat kalah 15 kali, tiga kali imbang, dan sekali menang atas Australia. Satu-satunya kemenangan Indonesia atas Australia tercipta pada 30 Agustus 1981. Kini tim tuan rumah Indonesia akan berusaha merebut kemenangan perdana di Grup C Kualifikasi Piala Dunia 2026 setelah bermain imbang 1-1 dengan Arab Saudi di babak pertama. Sementara itu, Australia berupaya bangkit dari kekalahan 0-1 lawan Bahrain di pertandingan pertama untuk menjaga peluang mereka lolos ke Piala Dunia 2026. Kini Indonesia berada di peringkat keempat Grup C dengan satu poin, sementara Australia berada di peringkat kelima dengan nol poin. Jadwal Siaran Langsung Timnas Indonesia vs Australia Stadion Utama Gelora Bung Karno, Senayan/ Selasa (10/9)/Pukul 19.00 WIB/Live RCTI/Live Streaming Vision+ [Gambas:Video CNN] (rhr)
--------------------------------------------------
Dokumen #6
Judul     : Jadwal Siaran Langsung dan Live Streaming Indonesia vs Australia
Tanggal   : Selasa, 10 Sep 2024 05:30 WIB
Kategori  : Olahraga
Similarity: 0.7780
Isi Berita:
Jadwal siaran langsung dan live streaming Timnas Indonesia vs Australia bisa diketahui dari artikel berikut. Timnas Indonesia vs Australia pada matchday kedua Grup C Kualifikasi Piala Dunia 2026 akan berlangsung hari ini Selasa (10/9) malam WIB di Stadion Utama Gelora Bung Karno, Senayan. Pertandingan Indonesia vs Australia bisa ditonton secara langsung di RCTI mulai pukul 19.00 WIB. Pilihan Redaksi Momen Timnas Indonesia Hajar Australia 1-0 di Kualifikasi Piala Dunia Reaksi Calvin Verdonk Usai Followers Instagram Tembus 1 Juta Wasit Kontroversial Salman Falahi Pimpin Laga Indonesia vs Australia Selain itu laga Indonesia vs Australia juga bisa disaksikan melalui live streaming di Vision+ juga pada pukul 19.00 WIB. Tuan rumah Indonesia mengincar kemenangan perdana di Grup C Kualifikasi Piala Dunia 2026 setelah bermain imbang 1-1 dengan Arab Saudi di babak pertama. Sementara itu, Australia berupaya bangkit dari kekalahan 0-1 lawan Bahrain di pertandingan pertama untuk menjaga peluang mereka lolos ke Piala Dunia 2026. Kini Indonesia berada di peringkat keempat Grup C dengan satu poin, sementara Australia berada di peringkat kelima dengan nol poin. Pada pertandingan ini Timnas Indonesia dipastikan akan mendapat dukungan penuh dari puluhan ribu suporter Garuda. Hal itu dipastikan karena seluruh tiket Indonesia vs Australia di Stadion GBK telah terjual habis. Dukungan pemain ke-12 Indonesia ini diharapkan bisa memberikan tambahan semangat dan kepercayaan diri para penggawa Garuda untuk mengalahkan Australia. Jadwal Siaran Langsung dan Live Streaming Indonesia vs Australia Stadion Utama Gelora Bung Karno, Senayan/ Selasa (10/9)/Pukul 19.00 WIB/Live RCTI/Live Streaming Vision+ [Gambas:Video CNN] (rhr)
--------------------------------------------------
Dokumen #7
Judul     : Jadwal Grup C Kualifikasi Piala Dunia Hari Ini Termasuk Indonesia
Tanggal   : Selasa, 10 Sep 2024 04:30 WIB
Kategori  : Olahraga
Similarity: 0.7280
Isi Berita:
Seluruh atau enam kontestan Grup C putaran ketiga Kualifikasi Piala Dunia 2026 Zona Asia akan bertanding hari ini Selasa (10/9) termasuk Timnas Indonesia vs Australia. Tiga pertandingan matchday kedua Grup C Kualifikasi Piala Dunia 2026 akan berlangsung hari ini Selasa (10/9) malam WIB. Ketiga pertandingan tersebut adalah China vs Arab Saudi, Indonesia vs Australia, dan Bahrain vs Jepang. Pilihan Redaksi Momen Timnas Indonesia Hajar Australia 1-0 di Kualifikasi Piala Dunia 6 Muka Baru Timnas Indonesia yang Bisa Bungkam Australia Reaksi Calvin Verdonk Usai Followers Instagram Tembus 1 Juta Pertandingan China vs Arab Saudi dan Indonesia vs Australia akan digelar berbarengan pada Selasa (10/9) pukul 19.00 WIB. Laga China vs Arab Saudi akan digelar di Stadion Dalian Suoyuwan Football, Dalian. Sedangkan laga Indonesia vs Australia akan berlangsung di Stadion Utama Gelora Bung Karno, Senayan. Pertandingan Indonesia vs Australia bisa ditonton secara langsung di RCTI. Selain itu laga Indonesia vs Australia juga bisa disaksikan melalui live streaming di Vision+. Sementara itu, pertandingan Bahrain vs Jepang akan digelar di Bahrain National Stadium, Riffa, pada Selasa (10/9) pukul 23.00 WIB. Laga Bahrain vs Jepang juga dapat ditonton melalui siaran langsung di RCTI. Selain itu pertandingan Bahrain vs Jepang bisa disaksikan lewat live streaming di Vision+. Pada klasemen Grup C, Jepang kini memimpin dengan torehan tiga poin disusul Bahrain dengan poin yang sama. Kemudian di peringkat ketiga ditempati Arab Saudi dengan satu poin diikuti Indonesia di posisi keempat dengan poin yang sama. Sementara Australia kini berada di posisi kelima dengan nol poin, kemudian China di dasar klasemen dengan nol poin. Jadwal Grup C Kualifikasi Piala Dunia 2026, Selasa (10/9): 19.00 WIB China vs Arab Saudi19.00 WIB Indonesia vs Arab Saudi23.00 WIB Bahrain vs Jepang [Gambas:Video CNN] (rhr)
--------------------------------------------------

Jumlah dokumen yang ditampilkan: 7
==================================================